### PR TITLE
Change version to const (compatibility with Pressbooks 3.9.9)

### PR DESCRIPTION
**Pull request by greatislander**

### CODE REVIEW

**Comment by bdolor** [comment]
So, this is to resolve a breaking change in PB? By merging this PR, the latest version of mPDF will no longer work with versions of PB < 3.9.9?

**Comment by greatislander** [comment]
Correct.

**Comment by bdolor** [comment]
should we adjust this accordingly? https://github.com/BCcampus/pressbooks-mpdf/blob/dev/pressbooks-mpdf.php#L66

**Comment by greatislander** [comment]
Yes, sorry! In my haste to get you a patch I neglected that. I can make that change and push an update to the PR.

**Pull request merged**
